<?php

namespace App\Models\Salud;

use Illuminate\Database\Eloquent\Model;

class PadronJuntos extends Model
{
    protected $table = 'sal_padron_juntos'; 

    public $timestamps = false; 

    protected $fillable = [
        'unidad_territorial_res',
        'ubigeo_res',
        'departamento_res',
        'provincia_res',
        'distrito_res',
        'centro_poblado_res',
        'codigo_hogar',
        'id_hogar',
        'dni_titular',
        'nombre_titular',
        'paterno_titular',
        'materno_titular',
        'id_mo',
        'tipo_doc_mo',
        'dni_mo',
        'fecha_nacimiento_mo',
        'nombre_mo',
        'paterno_no',
        'materno_mo',
        'sexo_mo',
        'celular_titular',
        'departamento_eess',
        'provincia_eess',
        'distrito_eess',
        'nombre_eess_mo',
        'departamento_eess_ultima_atencion',
        'provincia_eess_ultima_atencion',
        'distrito_eess_ultima_atencion',
        'nombre_eess_ultima_atencion',
        'red_ultima_atencion',
        'microred_ultima_atencion',
        'edad_mes_evaluacion',
        'rango_edad',
        'nino_cunamas',
        'compromiso_1',
        'tpi',
        'fecha_control_rn1',
        'fecha_control_rn2',
        'fecha_control_rn3',
        'fecha_control_rn4',
        'cumple_control_rn',
        'fecha_control_1',
        'fecha_control_2',
        'fecha_control_3',
        'fecha_control_4',
        'fecha_control_5',
        'fecha_control_6',
        'fecha_control_7',
        'fecha_control_8',
        'fecha_control_9',
        'fecha_control_10',
        'fecha_control_11',
        'fecha_control_12',
        'fecha_control_14',
        'fecha_control_16',
        'fecha_control_18',
        'fecha_control_20',
        'fecha_control_22',
        'cumple_cred',
        'fecha_neumococo_2',
        'fecha_neumococo_4',
        'fecha_neumococo_12',
        'cumple_neumococo',
        'fecha_rotavirus_2',
        'fecha_rotavirus_4',
        'cumple_rotavirus',
        'fecha_pentavalente_2',
        'fecha_pentavalente_4',
        'fecha_pentavalente_6',
        'cumple_pentavalente',
        'fecha_spr_12',
        'fecha_spr_18',
        'cumple_spr',
        'fecha_dosaje_6',
        'fecha_dosaje_12',
        'fecha_dosaje_18',
        'cumple_dosaje',
        'fecha_suplemento_0',
        'fecha_suplemento_4',
        'fecha_suplemento_5',
        'fecha_suplemento_6',
        'fecha_suplemento_7',
        'fecha_suplemento_8',
        'fecha_suplemento_9',
        'fecha_suplemento_10',
        'fecha_suplemento_11',
        'fecha_suplemento_12',
        'fecha_suplemento_13',
        'fecha_suplemento_14',
        'fecha_suplemento_15',
        'fecha_suplemento_16',
        'fecha_suplemento_17',
        'fecha_suplemento_18',
        'fecha_suplemento_19',
        'fecha_suplemento_20',
        'fecha_suplemento_21',
        'fecha_suplemento_22',
        'fecha_suplemento_23',
        'cumple_inicio_hierro',
        'cumple_hierro',
        'cumple_paquete',
        'cuenta_con_dni_cnv',
        'escala_prioridad_afa',
        'nombre_gestor_local',
        'nombre_ctz',
        'nino_con_anemia_minsa',
        'diagnostico_proyecto_anemia',
        'numero_acompanamiento_hogar',
        'fecha_ultimo_acompanamiento',
    ];

}

