<?php
namespace App\Exports\Salud;

use App\Models\Salud\PadronSeguimiento;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class SaludPadronSeguimientoExport implements FromCollection, WithHeadings
{ protected $id_grupo;
  protected $campo2;
  protected $filtro2;

  public function __construct($filtro1, $campo2, $filtro2)
  {
      $this->id_grupo = $filtro1;
      $this->campo2 = $campo2;
      $this->filtro2 = $filtro2;
  }

  public function collection()
  {   
      $query = PadronSeguimiento::where($this->campo2, $this->filtro2);      

      if ($this->id_grupo == 1) {
        $query->where('Edad_Anio', 0)->where('Edad_Mes', 0);
      }
      else
      {   $query->where('Edad_Anio', $this->id_grupo-2);
          if ($this->id_grupo == 2) {
              $query->where('Edad_Mes','>', 0);
          }
      }
      
      return $query->get();
  }

  public function headings(): array
  {
      return [
       'id'=>'id',
       'provincia'=>'Provincia',
       'ubigeo'=>'Ubigeo',
       'distrito'=>'Distrito',
       'renaes'=>'renaes',
       'red'=>'Red',
       'microred'=>'MicroRed',
       'eess'=>'EESS',
       'cnv'=>'CNV',
       'dni'=>'DNI',
       'nombre_nino'=>'nino',
       'fecha_nacimiento'=>'f_nacimiento',
       'edad_anio'=>'Edad_Anio',
       'edad_mes'=>'Edad_Mes',
       'edad_dias'=>'Edad_dias',
       'celular'=>'telefono',
       'direccion'=>'direccion',
       'cuna_mas_dni'=>'CUNA_MAS_DNI',
       'cuna_mas_cnv'=>'CUNA_MAS_CNV',
       'prog_juntos_dni'=>'PROG_JUNTOS_DNI',
       'prog_juntos_cnv'=>'PROG_JUNTOS_CNV',
       'compromiso_1_dni'=>'COMPROMISO_1_DNI',
       'compromiso_1_cnv'=>'COMPROMISO_1_CNV',
       'bajo_peso'=>'bajo_peso',
       'prematuro'=>'prematuro',
       'f_hb1'=>'f_hb1',
       'Rhb1'=>'Rhb1',
       'edad_hb1'=>'edad_hb1',
       'f_hb2'=>'f_hb2',
       'Rhb2'=>'Rhb2',
       'edad_hb2'=>'edad_hb2',
       'f_hb3'=>'f_hb3',
       'Rhb3'=>'Rhb3',
       'edad_hb3'=>'edad_hb3',
       'f_hb4'=>'f_hb4',
       'Rhb4'=>'Rhb4',
       'edad_hb4'=>'edad_hb4',
       'f_hb5'=>'f_hb5',
       'Rhb5'=>'Rhb5',
       'edad_hb5'=>'edad_hb5',
       'f_hb6'=>'f_hb6',
       'Rhb6'=>'Rhb6',
       'edad_hb6'=>'edad_hb6',
       'f_ane1'=>'f_ane1',
       'hb_ane1'=>'hb_ane1',
       'edad_ane1'=>'edad_ane1',
       'f_ane2'=>'f_ane2',
       'hb_ane2'=>'hb_ane2',
       'edad_ane2'=>'edad_ane2',
       'f_ane3'=>'f_ane3',
       'hb_ane3'=>'hb_ane3',
       'edad_ane3'=>'edad_ane3',
       'f_sup1'=>'f_sup1',
       'lab_sup1'=>'lab_sup1',
       'edad_sup1'=>'edad_sup1',
       'f_sup2'=>'f_sup2',
       'lab_sup2'=>'lab_sup2',
       'edad_sup2'=>'edad_sup2',
       'f_sup3'=>'f_sup3',
       'lab_sup3'=>'lab_sup3',
       'edad_sup3'=>'edad_sup3',
       'f_sup4'=>'f_sup4',
       'lab_sup4'=>'lab_sup4',
       'edad_sup4'=>'edad_sup4',
       'f_sup5'=>'f_sup5',
       'lab_sup5'=>'lab_sup5',
       'edad_sup5'=>'edad_sup5',
       'f_sup6'=>'f_sup6',
       'lab_sup6'=>'lab_sup6',
       'edad_sup6'=>'edad_sup6',
       'f_sup7'=>'f_sup7',
       'lab_sup7'=>'lab_sup7',
       'edad_sup7'=>'edad_sup7',
       'f_sup8'=>'f_sup8',
       'lab_sup8'=>'lab_sup8',
       'edad_sup8'=>'edad_sup8',
       'f_sup9'=>'f_sup9',
       'lab_sup9'=>'lab_sup9',
       'edad_sup9'=>'edad_sup9',
       'f_sup10'=>'f_sup10',
       'lab_sup10'=>'lab_sup10',
       'edad_sup10'=>'edad_sup10',
       'f_sup11'=>'f_sup11',
       'lab_sup11'=>'lab_sup11',
       'edad_sup11'=>'edad_sup11',
       'f_sup12'=>'f_sup12',
       'lab_sup12'=>'lab_sup12',
       'edad_sup12'=>'edad_sup12',
       'f_sup13'=>'f_sup13',
       'lab_sup13'=>'lab_sup13',
       'edad_sup13'=>'edad_sup13',
       'f_sup14'=>'f_sup14',
       'lab_sup14'=>'lab_sup14',
       'edad_sup14'=>'edad_sup14',
       'f_sup15'=>'f_sup15',
       'lab_sup15'=>'lab_sup15',
       'edad_sup15'=>'edad_sup15',
       'f_sup16'=>'f_sup16',
       'lab_sup16'=>'lab_sup16',
       'edad_sup16'=>'edad_sup16',
       'f_sup17'=>'f_sup17',
       'lab_sup17'=>'lab_sup17',
       'edad_sup17'=>'edad_sup17',
       'f_sup18'=>'f_sup18',
       'lab_sup18'=>'lab_sup18',
       'edad_sup18'=>'edad_sup18',
       'f_sup19'=>'f_sup19',
       'lab_sup19'=>'lab_sup19',
       'edad_sup19'=>'edad_sup19',
       'f_sup20'=>'f_sup20',
       'lab_sup20'=>'lab_sup20',
       'edad_sup20'=>'edad_sup20',
       'f_recup1'=>'f_recup1',
       'tipoD_recup1'=>'tipoD_recup1',
       'hb_recup1'=>'hb_recup1',
       'edad_recup1'=>'edad_recup1',
       'f_recup2'=>'f_recup2',
       'tipoD_recup2'=>'tipoD_recup2',
       'hb_recup2'=>'hb_recup2',
       'edad_recup2'=>'edad_recup2',
       'f_credrn1'=>'f_credrn1',
       'edad_credrn1'=>'edad_credrn1',
       'f_credrn2'=>'f_credrn2',
       'edad_credrn2'=>'edad_credrn2',
       'f_credrn3'=>'f_credrn3',
       'edad_credrn3'=>'edad_credrn3',
       'f_credrn4'=>'f_credrn4',
       'edad_credrn4'=>'edad_credrn4',
       'f_cred01'=>'f_cred01',
       'edad_cred01'=>'edad_cred01',
       'f_cred02'=>'f_cred02',
       'edad_cred02'=>'edad_cred02',
       'f_cred03'=>'f_cred03',
       'edad_cred03'=>'edad_cred03',
       'f_cred04'=>'f_cred04',
       'edad_cred04'=>'edad_cred04',
       'f_cred05'=>'f_cred05',
       'edad_cred05'=>'edad_cred05',
       'f_cred06'=>'f_cred06',
       'edad_cred06'=>'edad_cred06',
       'f_cred07'=>'f_cred07',
       'edad_cred07'=>'edad_cred07',
       'f_cred08'=>'f_cred08',
       'edad_cred08'=>'edad_cred08',
       'f_cred09'=>'f_cred09',
       'edad_cred09'=>'edad_cred09',
       'f_cred010'=>'f_cred010',
       'edad_cred010'=>'edad_cred010',
       'f_cred011'=>'f_cred011',
       'edad_cred011'=>'edad_cred011',
       'f_cred11'=>'f_cred11',
       'edad_cred11'=>'edad_cred11',
       'f_cred12'=>'f_cred12',
       'edad_cred12'=>'edad_cred12',
       'f_cred13'=>'f_cred13',
       'edad_cred13'=>'edad_cred13',
       'f_cred14'=>'f_cred14',
       'edad_cred14'=>'edad_cred14',
       'f_cred15'=>'f_cred15',
       'edad_cred15'=>'edad_cred15',
       'f_cred16'=>'f_cred16',
       'edad_cred16'=>'edad_cred16',
       'f_cred21'=>'f_cred21',
       'edad_cred21'=>'edad_cred21',
       'f_cred22'=>'f_cred22',
       'edad_cred22'=>'edad_cred22',
       'f_cred23'=>'f_cred23',
       'edad_cred23'=>'edad_cred23',
       'f_cred24'=>'f_cred24',
       'edad_cred24'=>'edad_cred24',
       'f_cred31'=>'f_cred31',
       'edad_cred31'=>'edad_cred31',
       'f_cred32'=>'f_cred32',
       'edad_cred32'=>'edad_cred32',
       'f_cred33'=>'f_cred33',
       'edad_cred33'=>'edad_cred33',
       'f_cred34'=>'f_cred34',
       'edad_cred34'=>'edad_cred34',
       'f_cred41'=>'f_cred41',
       'edad_cred41'=>'edad_cred41',
       'f_cred42'=>'f_cred42',
       'edad_cred42'=>'edad_cred42',
       'f_cred43'=>'f_cred43',
       'edad_cred43'=>'edad_cred43',
       'f_cred44'=>'f_cred44',
       'edad_cred44'=>'edad_cred44',
       'f_vhep'=>'f_vhep',
       'edad_vhep'=>'edad_vhep',
       'f_vbcg'=>'f_vbcg',
       'edad_vbcg'=>'edad_vbcg',
       'f_vpenta1'=>'f_vpenta1',
       'edad_vpenta1'=>'edad_vpenta1',
       'f_vpenta2'=>'f_vpenta2',
       'edad_vpenta2'=>'edad_vpenta2',
       'f_vpenta3'=>'f_vpenta3',
       'edad_vpenta3'=>'edad_vpenta3',
       'f_vipv1'=>'f_vipv1',
       'edad_vipv1'=>'edad_vipv1',
       'f_vipv2'=>'f_vipv2',
       'edad_vipv2'=>'edad_vipv2',
       'f_vapo1'=>'f_vapo1',
       'edad_vapo1'=>'edad_vapo1',
       'f_vapo2'=>'f_vapo2',
       'edad_vapo2'=>'edad_vapo2',
       'f_vapo3'=>'f_vapo3',
       'edad_vapo3'=>'edad_vapo3',
       'f_vapo4'=>'f_vapo4',
       'edad_vapo4'=>'edad_vapo4',
       'f_vapo5'=>'f_vapo5',
       'edad_vapo5'=>'edad_vapo5',
       'f_vrota1'=>'f_vrota1',
       'edad_vrota1'=>'edad_vrota1',
       'f_vrota2'=>'f_vrota2',
       'edad_vrota2'=>'edad_vrota2',
       'f_vrota3'=>'f_vrota3',
       'edad_vrota3'=>'edad_vrota3',
       'f_vneumo1'=>'f_vneumo1',
       'edad_vneumo1'=>'edad_vneumo1',
       'f_vneumo2'=>'f_vneumo2',
       'edad_vneumo2'=>'edad_vneumo2',
       'f_vneumo3'=>'f_vneumo3',
       'edad_vneumo3'=>'edad_vneumo3',
       'f_vneumo4'=>'f_vneumo4',
       'edad_vneumo4'=>'edad_vneumo4',
       'f_vinflu1'=>'f_vinflu1',
       'edad_vinfu1'=>'edad_vinfu1',
       'f_vinflu2'=>'f_vinflu2',
       'edad_vinfu2'=>'edad_vinfu2',
       'f_vspr1'=>'f_vspr1',
       'edad_vspr1'=>'edad_vspr1',
       'f_vspr2'=>'f_vspr2',
       'edad_vspr2'=>'edad_vspr2',
       'f_vama'=>'f_vama',
       'edad_vama'=>'edad_vama',
       'f_vdpt1'=>'f_vdpt1',
       'edad_vdpt1'=>'edad_vdpt1',
       'f_vdpt2'=>'f_vdpt2',
       'edad_vdpt2'=>'edad_vdpt2',
      ];
  }
}
